name: fraud-detection-project
channels:
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn
  - jupyter
  - shap
  - lime
  - pyyaml
  - logging
  - pip
  - pip:
      - xgboost
      - lightgbm
      - catboost